apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: nginx-configmap
    files: 
      - html/index.html
generatorOptions:
  disableNameSuffixHash: true # use a static name
resources:
  - k8s/nginx-service.yaml
  - k8s/nginx-deployment.yaml