apiVersion: v1
kind: Service
metadata:
  name: nginx-skaffold
spec:
  type: NodePort
  selector:
    app: nginx-skaffold
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
