apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-skaffold
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-skaffold
  template:
    metadata:
      labels:
        app: nginx-skaffold
    spec:
      containers:
        - name: nginx
          image: nginx-skaffold  
          ports:
            - containerPort: 80

